### ISSUE TITLE
google.auth.exceptions.RefreshError - Refresh Token Expired or Revoked Error in Python when trying to run

### ISSUE THREAD

**Issue by iPrakharV** [AbhisarAnand/Sync-Assignments#1]
I encountered an issue while trying to refresh OAuth2 tokens using Python, specifically when working with the oauth2client and google-auth libraries to authenticate Gmail API access. The refresh token seems to be expired or revoked, causing the following error:

```
  Traceback (most recent call last):
    File "/Sync-Assignments/main.py", line 10, in <module>
      reader.authenticate()
    File "/Sync-Assignments/Google/GmailReader.py", line 26, in authenticate
      creds.refresh(Request())
    File "/Python/3.9/lib/python/site-packages/google/oauth2/credentials.py", line 409, in refresh
      self._client.refresh_grant()
    File "/Python/3.9/lib/python/site-packages/google/oauth2/_client.py", line 68, in _handle_error_response
      raise exceptions.RefreshError(
  google.auth.exceptions.RefreshError: ('invalid_grant: Token has been expired or revoked.', {'error': 'invalid_grant', 'error_description': 'Token has been expired or revoked.'})
```

Steps to Reproduce:
	1. Run 
`	python3 Main.py
`
Actual Behavior:
The application fails to run and raises the invalid_grant error stating the token has been expired or revoked.

Environment:
	•	macOS (as shown in screenshot)
	•	Python 3.9
	•	google-auth version
	
<img width="1649" alt="IMG_0161" src="https://github.com/user-attachments/assets/33441fbc-f72e-4d3e-8538-16831faacadc">

**Comment by AbhisarAnand** [comment]
fixed it
